### ISSUE TITLE
SILAC - only LIGHT pair but no HEAVY

### ISSUE THREAD

**Issue by heejongkim** [protcode/isob#8]
Hi,

After digging down several days to figure out the issue, I feel I'm missing something I can't find the source of the problem at a reasonable timescale so I'm opening this issue. I hope I can get some insights from you.

The circumstance is simple.
I followed the MS1 SILAC quant method from this paper: https://www.nature.com/articles/s41467-018-03106-1
And I believe I followed it fairly well but it seems isobarquant only picks up LIGHT channel but not any other channels by seeing the log (only LIGHT frequency is shown).
And peptide and protein results header look like the followings:
* Peptide result header:
protein_group_no	protein_id	sequence	modifications	mw	precursor_mz	charge_state	ppm_error	score	fdr_at_score	delta mod	rank	msms_id	source_file	retention time	peak_intensity	s2i	p2t	is_unique	in_quantification_of_protein	in_protein_inference	in_top3	seq_start	seq_end	is_decoy	prior ion ratio	least squares	ms1 source	sig_LIGHT
* Protein result header:
protein_group_no	protein_id	description	gene_name	mw	top3	protein_fdr	max_score	total_score	ssm	upm	fqssm	qssm	qupm	reference_label	signal_sum_LIGHT	rel_fc_LIGHT	delta_conf_LIGHT

I did check some portions of MS1QuantController.py and other relevant sources but I had no luck.

Commandlines:
python preMascot.py --datadir C:\location --quant SILAC3
after this and mascot search
python postMascot.py --datadir C:\location --mergeresults yes

The followings are the cfg files--
---preMascot.cfg
[runtime]
paramconversion:    {'path': ['datadir']}
datadir:            C:\josue\DevAtlas_Brain
quant:              4

[logging]
logdir:             logs
logfile:            preMascot.log
screenlevel:        WARNING
loglevel:           WARNING

[general]
paramconversion:    {'int': ['thread_count'],  'bool': ['printchargedata']}
tolppm:             10
tolmda:             20
beforepeak:         0.5
afterpeak:          0.5
thread_count:       10
printchargedata:    yes

---postMascot.cfg
[runtime]
paramconversion:    {'path': ['datadir'], 'bool': ['mergeresults']}
datadir:            c:/myproject
mergeresults:       yes

[logging]
logdir:             logs
logfile:            postMascot.log
screenlevel:        DEBUG
loglevel:           DEBUG

[general]
paramconversion:    {'bool': ['run_corrects2iquant'], 'int': ['thread_count'], 'float': ['fdrthreshold']}
minhooklength:      6
delta:              10
fdrthreshold:       0.01
run_corrects2iquant: yes
thread_count: 10

[quantification]
# reference used for quantification default is
# last (last in series when ordered by reporter
# ion mass - ie for TMT10 126, 127L, 127H, 128L,
# 128H, 129L, 129H, 130L, 130H, 131L
reference:          first

If you can guide me where to look for the potential causes, I will be more than happy.

Thanks!

**Comment by tobymathieson** [comment]
Hi heejongkim, Can you tell me what your Mascot settings are ? If you're using the 'standard' SILAC settings they won't work at the moment. If you change your Mascot modfiications as detailed below isobarQuant should work ok

Label:13C(6)15N(2) -->  SILAC:K+8
Label:13C(6)15N(4) -->  SILAC:R+10

Let me know if that solves your problem

**Comment by heejongkim** [comment]
Perfect.
I changed the modification names to SILAC:K+8 and SILAC:R+10 accordingly in Mascot and postMascot successfully picked up the HEAVY part. Now I'm testing with multiple files to see if it works.
Thank you!
