### ISSUE TITLE
RuntimeWarning: Mean of empty slice

### ISSUE THREAD

**Issue by heejongkim** [protcode/isob#9]
Hi,

As I'm doing the combined postMascot process, one line of warning was caught by my eyes.

C:\py279_32\lib\site-packages\numpy\core\_methods.py:55: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)

I'm not sure if I need to be concerned about this warning or not but, generally, if I ignore it, it comes back to me as a huge problem so I'd like acknowledge it so that I can move on.

Can you please help me understand where (at which stage) it gets produced and why?

Thank you!

best,
hee jong kim

---- except from the commandline output ----
postMascot    : PROCESS  Finished proteinInference successfully for C:\josue\Brain_merged_results_20180927_2239.hdf5
postMascot    : PROCESS  running protein quant for Brain_merged_results_20180927_2239.hdf5
C:\py279_32\lib\site-packages\numpy\core\_methods.py:55: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
postMascot    : PROCESS  Finished proteinQuantification successfully for C:\josue\Brain_merged_results_20180927_2239.hdf5
postMascot    : PROCESS  creating output for files like results_20180927_2239.hdf5

**Comment by tobymathieson** [comment]
hi hee jong kim, 
That warning is thrown by numpy (as you can see from the warning itself) it occurs during the protein quantification stage and likely applies to a protein that has one missing label;. 
You do not need to worry about it - your data will be just fine
best
Toby
